# -*- coding: utf-8 -*-
"""Pr2(AIML).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzKN8O3hy7iYmtX-onZZk7CONuHtOXIB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('city_day.csv')

df.head()

df.info()

print("\nDescriptive Statistics:")
df.describe()

df.isnull().sum()

print(df.isnull().sum())
print(df[['PM2.5', 'PM10']].describe())

pollutants = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3']
for col in pollutants:
    df[col].fillna(df[col].mean(), inplace=True)

for col in df.select_dtypes(include='number').columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].median(), inplace=True)

df.isnull().sum()

corr = df[pollutants].corr()
corr

top_cities = df.groupby('City')['Calculated_AQI'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 5))
top_cities.plot(kind='bar', color='maroon')
plt.title("Top 10 Most Polluted Cities (Avg AQI)")
plt.xlabel("City")
plt.ylabel("Average AQI")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.boxplot([df[col].dropna() for col in pollutants], labels=pollutants)
plt.title("Boxplot of Pollutants")
plt.ylabel("Concentration")
plt.grid(True)
plt.tight_layout()
plt.show()

corr = df[pollutants].corr()
fig, ax = plt.subplots(figsize=(8, 6))
heatmap = ax.imshow(corr, cmap='coolwarm', interpolation='nearest')
plt.colorbar(heatmap, label='Correlation')

ax.set_xticks(range(len(pollutants)))
ax.set_yticks(range(len(pollutants)))
ax.set_xticklabels(pollutants, rotation=45)
ax.set_yticklabels(pollutants)
ax.set_title("Pollutant Correlation Heatmap")

# Add correlation numbers on the heatmap
for i in range(len(pollutants)):
    for j in range(len(pollutants)):
        ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha='center', va='center', color='black')

plt.tight_layout()
plt.show()

delhi_data = df[df['City'] == 'Delhi'].sort_values('Date')
plt.figure(figsize=(10, 4))
plt.plot(delhi_data['Date'], delhi_data['PM2.5'], color='blue')
plt.title("PM2.5 Levels Over Time in Delhi")
plt.xlabel("Date")
plt.ylabel("PM2.5 (µg/m³)")
plt.grid(True)
plt.tight_layout()
plt.show()

